qa:
  base_url: "https://iq4.rainbird.com"
  timeout_sec: 40

stage:
  base_url: "https://iq4staging.usw2.rainbird.com"
  timeout_sec: 40

prod:
  base_url: "https://iq4.rainbird.com"
  timeout_sec: 40
